apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: openshift-gitops
spec:
  project: default
  source: 
    plugin:
      name: manifest-validator    
    repoURL: https://github.com/ricmitch-commits/openshift-local.git
    targetRevision: main
    path: manifests/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
